### ISSUE TITLE
bowsers sub won't apear

### ISSUE THREAD

**Issue by Twanvanb1** [DarioSamo/sm64rt#3]
Bowsers submarine isn't there in dire, dire docks

![image](https://user-images.githubusercontent.com/78142253/117358708-c35f0f80-aeb6-11eb-88dd-b6359f191ccf.png)

**Comment by DarioSamo** [comment]
I thought the submarine won't appear if you skip the door?

**Comment by DarioSamo** [comment]
In any case, I suggest checking against sm64ex-nightly if the behavior is not correct first, as I don't think this has anything to do with my changes.

**Comment by DarioSamo** [comment]
Did you by chance defeat bowser in the fire world by some method?

**Comment by DarioSamo** [comment]
I just checked and it's definitely there on master.

Are you sure your save is not just messed up and you defeated bowser somehow?

![image](https://user-images.githubusercontent.com/538504/117365870-520f6480-ae96-11eb-8a17-c329ae2edf8f.png)

**Comment by Twanvanb1** [comment]
i have found the issue my save file is bugged.

**Comment by Twanvanb1** [comment]
> i have found the issue my save file is bugged.

Sorry for the false Issue
