### ISSUE TITLE
Additional Requirements

### ISSUE THREAD

**Issue by OopyDoopy** [DarioSamo/sm64rt#5]
One of my friend's tried installing this on a fresh windows 10 install.  They also needed to install VC 2015 and 2019 to get this working.  

Also, it does not work on Windows 10 1809.  I don't know what the oldest working build of Windows 10 is unfortunately, but maybe that info will help.

**Comment by DarioSamo** [comment]
Thank you.

I'm not sure why the VC 2015 redistributables would be required, as RT64 is only built with VS2019. I'll make sure to add VS2019 for now at least.

As for Windows 10, I think it's been confirmed to work in both 20H2 and 2004 at least. Maybe 1909 as well, although no solid confirmation on that one yet.

**Comment by DarioSamo** [comment]
Apparently the redistributable includes both versions, so only one executable is required. I've added both to the README.

I do not think older Windows 10 support will happen, as RT64 has been built with one of the latest versions of the Windows SDK.

Feel free to close this unless you have any more suggestions.

**Comment by OopyDoopy** [comment]
It's possible only VS 2019 was required, I don't know how confident they were in their assertion that VC 2015 is required.  Maybe list VC 2019 only and change it if anyone reports a problem.

**Comment by DarioSamo** [comment]
pcbuilder2 will integrate this repository soon, so I think it's fine to keep the instructions to those familiar with git anyway (I mean, it is GitHub after all).
