### ISSUE TITLE
fullscreen causes major performance decrease

### ISSUE THREAD

**Issue by Vbuck-gang** [DarioSamo/sm64rt#68]
**Describe the bug**
full screen causes fps to drop by more than half.
**To Reproduce**
1.  be in full screen 
2. done

**Expected behavior**
the small window shows the expected performance 120fps at 1440p
**Screenshots**
![Screenshot (126)](https://github.com/DarioSamo/sm64rt/assets/63995419/85a16f55-c9ad-47c0-bd70-f4c2dbb93c34)

![Screenshot (127)](https://github.com/DarioSamo/sm64rt/assets/63995419/d1afadba-f8b1-4780-8a95-769f635067ac)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22H2
**Additional context**
amd 7900 xt and 5900x with 32 gigs of ram

**Comment by DarioSamo** [comment]
Higher rendering resolution = lower performance.
